export const brandNewDeck = [
  // Spades (Black)
  { value: '2', suit: 'spade', color: 'black' },
  { value: '3', suit: 'spade', color: 'black' },
  { value: '4', suit: 'spade', color: 'black' },
  { value: '5', suit: 'spade', color: 'black' },
  { value: '6', suit: 'spade', color: 'black' },
  { value: '7', suit: 'spade', color: 'black' },
  { value: '8', suit: 'spade', color: 'black' },
  { value: '9', suit: 'spade', color: 'black' },
  { value: '10', suit: 'spade', color: 'black' },
  { value: 'J', suit: 'spade', color: 'black' },
  { value: 'Q', suit: 'spade', color: 'black' },
  { value: 'K', suit: 'spade', color: 'black' },
  { value: 'A', suit: 'spade', color: 'black' },

  // Clubs (Black)
  { value: '2', suit: 'club', color: 'black' },
  { value: '3', suit: 'club', color: 'black' },
  { value: '4', suit: 'club', color: 'black' },
  { value: '5', suit: 'club', color: 'black' },
  { value: '6', suit: 'club', color: 'black' },
  { value: '7', suit: 'club', color: 'black' },
  { value: '8', suit: 'club', color: 'black' },
  { value: '9', suit: 'club', color: 'black' },
  { value: '10', suit: 'club', color: 'black' },
  { value: 'J', suit: 'club', color: 'black' },
  { value: 'Q', suit: 'club', color: 'black' },
  { value: 'K', suit: 'club', color: 'black' },
  { value: 'A', suit: 'club', color: 'black' },

  // Hearts (Red)
  { value: '2', suit: 'heart', color: 'red' },
  { value: '3', suit: 'heart', color: 'red' },
  { value: '4', suit: 'heart', color: 'red' },
  { value: '5', suit: 'heart', color: 'red' },
  { value: '6', suit: 'heart', color: 'red' },
  { value: '7', suit: 'heart', color: 'red' },
  { value: '8', suit: 'heart', color: 'red' },
  { value: '9', suit: 'heart', color: 'red' },
  { value: '10', suit: 'heart', color: 'red' },
  { value: 'J', suit: 'heart', color: 'red' },
  { value: 'Q', suit: 'heart', color: 'red' },
  { value: 'K', suit: 'heart', color: 'red' },
  { value: 'A', suit: 'heart', color: 'red' },

  // Diamonds (Red)
  { value: '2', suit: 'diamond', color: 'red' },
  { value: '3', suit: 'diamond', color: 'red' },
  { value: '4', suit: 'diamond', color: 'red' },
  { value: '5', suit: 'diamond', color: 'red' },
  { value: '6', suit: 'diamond', color: 'red' },
  { value: '7', suit: 'diamond', color: 'red' },
  { value: '8', suit: 'diamond', color: 'red' },
  { value: '9', suit: 'diamond', color: 'red' },
  { value: '10', suit: 'diamond', color: 'red' },
  { value: 'J', suit: 'diamond', color: 'red' },
  { value: 'Q', suit: 'diamond', color: 'red' },
  { value: 'K', suit: 'diamond', color: 'red' },
  { value: 'A', suit: 'diamond', color: 'red' },
];
